### PR TITLE
Fixed all issues with last hercules update. (VIRT_GUILD disabled)

### PR DESCRIPTION
**Pull request by carloshenrq**
Now working without compile/warnings since lastest Hercules update.

### CODE REVIEW

**Comment by carloshenrq** [comment]
@dastgirp don't merge it. there're some bugs that i'm working on. i'll update here and after ask for review.

thank you.

**Comment by dastgirp** [comment]
@carloshenrq I have no error/warning in last hercules update.
Have you changed anything in plugin which caused the error/warnings?

**Comment by Vaans** [comment]
Me too, i don't have any errors in the last update.

**Comment by carloshenrq** [comment]
@dastgirp and @Vaans 
I've commented here

https://github.com/dastgirp/eBG/blob/9dc769c16046b60828da6039a6b35112998722a7/server/src/plugins/eBG_common.h#L55-L56

I've got some erros and warnings and i was try to fix them, but so many crashes when player join bg. (crash only with #VIRT_GUILD commented!!! without comment, no crashes)
Maybe a refactor is need in this plugin?

I don't really believe how you guys're still running since `inventory_to_sql` was removed from `char.h`, same for `class_` in `mmo_charstatus` and `MAX_SKILL` was changed to `MAX_SKILL_DB`.

**Comment by carloshenrq** [comment]
Those're the erros:

```
ExtendedBG.c: In function 'eBG_ChangeLeader':
ExtendedBG.c:1848:19: warning: unused variable 'color' [-Wunused-variable]
      unsigned int color;
                   ^
ExtendedBG.c:1847:11: warning: unused variable 'output' [-Wunused-variable]
      char output[100];
           ^
ExtendedBG.c: In function 'bg_guild_build_data':
ExtendedBG.c:3291:10: error: 'bg_guild' undeclared (first use in this function)
  memset(&bg_guild, 0, sizeof(bg_guild));
          ^
ExtendedBG.c:3291:10: note: each undeclared identifier is reported only once for each function it appears in
ExtendedBG.c: In function 'send_bg_memberlist_':
ExtendedBG.c:3659:28: warning: unused variable 'bgd' [-Wunused-variable]
  struct battleground_data *bgd = bg->team_search(sd->bg_id);
                            ^
AtCommands.inc: In function 'atcommand_order':
AtCommands.inc:224:22: error: 'sd_data' undeclared (first use in this function)
    GET_ORIG_GUILD_ID(sd_data->g->guild_id)
                      ^
ExtendedBG.c:154:43: note: in definition of macro 'GET_ORIG_GUILD_ID'
  #define GET_ORIG_GUILD_ID(ebg_guild_id) (ebg_guild_id) - EBG_GUILDSTART
                                           ^
AtCommands.inc: In function 'atcommand_leader':
AtCommands.inc:287:38: error: 'sd_data' undeclared (first use in this function)
  color = bg_colors[GET_ORIG_GUILD_ID(sd_data->g->guild_id)];
                                      ^
ExtendedBG.c:154:43: note: in definition of macro 'GET_ORIG_GUILD_ID'
  #define GET_ORIG_GUILD_ID(ebg_guild_id) (ebg_guild_id) - EBG_GUILDSTART
                                           ^
AtCommands.inc: In function 'atcommand_reportafk':
AtCommands.inc:353:38: error: 'sd_data' undeclared (first use in this function)
  color = bg_colors[GET_ORIG_GUILD_ID(sd_data->g->guild_id)];
                                      ^
ExtendedBG.c:154:43: note: in definition of macro 'GET_ORIG_GUILD_ID'
  #define GET_ORIG_GUILD_ID(ebg_guild_id) (ebg_guild_id) - EBG_GUILDSTART
                                           ^
In file included from ExtendedBG.c:6240:0:
ScriptCommands.inc: In function 'buildin_bg_info':
ScriptCommands.inc:1295:41: error: 'sd' undeclared (first use in this function)
  struct sd_p_data *sd_data = pdb_search(sd, false);
                                         ^
make[1]: *** [../../plugins/ExtendedBG.so] Error 1
```

```
ExtendedBG-char.c: In function 'inter_guild_tosql_pre':
ExtendedBG-char.c:422:8: error: 'struct guild_member' has no member named 'class_'
       m->class_, m->lv, m->exp, m->exp_payper, m->online, m->position, esc_name) )
        ^
ExtendedBG-char.c: In function 'inter_guild_fromsql_pre':
ExtendedBG-char.c:547:55: error: 'struct guild_member' has no member named 'class_'
    SQL->GetData(inter->sql_handle,  5, &data, NULL); m->class_ = atoi(data);
                                                       ^
ExtendedBG-char.c: In function 'chr_mmo_char_tosql_pre':
ExtendedBG-char.c:714:11: error: 'struct char_interface' has no member named 'inventory_to_sql'
   if (!chr->inventory_to_sql(p->inventory, MAX_INVENTORY, p->char_id))
           ^
ExtendedBG-char.c:722:3: error: too many arguments to function 'chr->memitemdata_to_sql'
   if (!chr->memitemdata_to_sql(p->cart, MAX_CART, p->char_id, TABLE_CART))
   ^
ExtendedBG-char.c:729:14: error: 'struct mmo_charstatus' has no member named 'storage'
  if( memcmp(p->storage.items, cp->storage.items, sizeof(p->storage.items)) ) {
              ^
ExtendedBG-char.c:729:33: error: 'struct mmo_charstatus' has no member named 'storage'
  if( memcmp(p->storage.items, cp->storage.items, sizeof(p->storage.items)) ) {
                                 ^
ExtendedBG-char.c:729:58: error: 'struct mmo_charstatus' has no member named 'storage'
  if( memcmp(p->storage.items, cp->storage.items, sizeof(p->storage.items)) ) {
                                                          ^
ExtendedBG-char.c:730:33: error: 'struct mmo_charstatus' has no member named 'storage'
   if (!chr->memitemdata_to_sql(p->storage.items, MAX_STORAGE, p->account_id, TABLE_STORAGE))
                                 ^
ExtendedBG-char.c:730:3: error: too many arguments to function 'chr->memitemdata_to_sql'
   if (!chr->memitemdata_to_sql(p->storage.items, MAX_STORAGE, p->account_id, TABLE_STORAGE))
   ^
ExtendedBG-char.c:852:5: error: 'struct mmo_charstatus' has no member named 'class_'
   (p->class_ != cp->class_) ||
     ^
ExtendedBG-char.c:852:19: error: 'struct mmo_charstatus' has no member named 'class_'
   (p->class_ != cp->class_) ||
                   ^
ExtendedBG-char.c:864:14: error: 'struct mmo_charstatus' has no member named 'class_'
    char_db, p->class_,
              ^
ExtendedBG-char.c:936:30: error: 'MAX_SKILL' undeclared (first use in this function)
   for( i = 0, count = 0; i < MAX_SKILL; ++i ) {
                              ^
ExtendedBG-char.c:936:30: note: each undeclared identifier is reported only once for each function it appears in
In file included from ExtendedBG-char.c:28:0:
ExtendedBG-char.c: In function 'plugin_init':
HPMHooking.h:49:53: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   (void)((HPMHOOK_pre_ ## ifname ## _ ## funcname)0 == (hook)), \
                                                     ^
ExtendedBG-char.c:1074:2: note: in expansion of macro 'addHookPre'
  addHookPre(inter_guild, tosql, inter_guild_tosql_pre);
  ^
HPMHooking.h:49:53: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   (void)((HPMHOOK_pre_ ## ifname ## _ ## funcname)0 == (hook)), \
                                                     ^
ExtendedBG-char.c:1078:2: note: in expansion of macro 'addHookPre'
  addHookPre(mapif, parse_BreakGuild, mapif_parse_BreakGuild_pre);
  ^
HPMHooking.h:49:53: warning: comparison of distinct pointer types lacks a cast [enabled by default]
   (void)((HPMHOOK_pre_ ## ifname ## _ ## funcname)0 == (hook)), \
                                                     ^
ExtendedBG-char.c:1079:2: note: in expansion of macro 'addHookPre'
  addHookPre(chr, mmo_char_tosql, chr_mmo_char_tosql_pre);
  ^
```

**Comment by carloshenrq** [comment]
The crash when joining bg:

```
No symbol table info available.
#1  0x00007ffff631137b in vsprintf () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff62f3517 in sprintf () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff09535b6 in update_ebg_idle (sd_=0x20, type=0x7ffff097a0c1) at ExtendedBG.c:5024
        output = "\020\341\377\377\377\177\000\000ֱ`\000\000\000\000\000\320\340\377\377\377\177\000\000(\035b", '\000' <repeats 13 times>, "\240\021\026\005", '\000' <repeats 12 times>, "\030\326\216\004", '\000' <repeats 12 times>, ",Z\201\001\000\000\000\000\210\341\377\377\377\177\000\000\000\000\000\000\000\000\000\000`\aO\000\000\000\000\000(\035b\000\000\000\000\000 \341\377\377\377\177\000\000,Z\201\001\000\000\000"
        bgd = 0x233b464
        data = 0x4581714
        sd = 0x51611a0
#4  0x00007ffff3b5fe05 in HP_pc_update_idle_time (sd=0x51611a0, type=BCIDLE_WALK)
    at HPMHooking/HPMHooking_map.Hooks.inc:66181
No locals.
#5  0x00000000004a0987 in clif_parse_WalkToXY (fd=80, sd=0x51611a0) at clif.c:11022
        x = 80
        y = 77
#6  0x000000000046632e in clif_parse (fd=12) at clif.c:22800
        parse_cmd_func = 0x0
        packet_len = 24
        sd = 0x51611a0
#7  0x000000000063b4be in do_sockets (next=96) at socket.c:1073
        rfd = {fds_bits = {4096, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 16365}
        ret = 0
#8  0x00000000004080d2 in main (argc=1, argv=0x7fffffffe3d8) at core.c:538
        next = 0
        retval = 6501984```
```

**Comment by dastgirp** [comment]
Ok, got it.
Most likely because we don't have VIRT_GUILD commented, I would advise you to not comment VIRT_GUILD as that would be default option and other option will be removed.

**Comment by dastgirp** [comment]
Closing this as we already have updated ebg

**Pull request closed without merging**
